name: Azure Kubernetes Service

on:
  workflow_dispatch:
env:
  REGISTRY: jsdays2021.azurecr.io
  AKS_NAME: aks-jsdays
  AKS_RG_NAME: rg-rg-javascript-days
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.AKS_NAME }}
        resource-group: ${{ env.AKS_RG_NAME }}
    
    - uses: azure/docker-login@v1
      name: Build and Push Container Image
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_TOKEN }}
    - run: |
        docker build . -t ${{ env.REGISTRY }}/paint:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/paint:${{ github.sha }}

    - uses: azure/k8s-deploy@v1
      name: Deploy Namespaces
      with:
        manifests: |
          k8s/namespace.yml
    - uses: azure/k8s-deploy@v1
      name: Deploy Application
      with:
        manifests: |
          k8s/app/deployment.yml
          k8s/app/service.yml
        images: |
          ${{ env.REGISTRY }}/paint:${{ github.sha }}
        namespace: js-days
